CREATE TABLE IF NOT EXISTS PARTIDA (
    ID SERIAL PRIMARY KEY,
    HOST_IP VARCHAR(50) ,
    HOST_NAME VARCHAR(50) ,
    GUEST_NAME VARCHAR(50) ,
    GUEST_IP VARCHAR(50) ,
    TABLERO VARCHAR(250),
    TURNO VARCHAR(50) ,
    EXISTE_GANADOR BOOLEAN,
    GANADOR VARCHAR(50)
);
